# GoReleaser configuration for KubeVirt VM Feature Manager
version: 2

before:
  hooks:
    # Clean up go.mod and go.sum to ensure they're up to date
    - go mod tidy
    # Run code generators
    - go generate ./...

builds:
  - id: webhook
    main: ./cmd/webhook
    binary: webhook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: webhook
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Enhancements'
      regexp: '^.*?enhance(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

# Ko - modern Go container builder (no Dockerfile needed!)
kos:
  - id: webhook
    build: webhook
    base_image: gcr.io/distroless/static-debian12:nonroot
    # Repositories to push to. Templates are NOT supported here.
    # Set dynamically via KO_DOCKER_REPO in CI, or use literal repository name.
    repositories:
      - "ghcr.io/jaevans/kubevirt-vm-feature-manager"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"

# SBOM generation
sboms:
  - artifacts: archive
    ids:
      - webhook

# Sign artifacts (disabled in snapshot mode)
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

# Docker image signing (disabled in snapshot mode)
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: all
    output: true
    args:
      - 'sign'
      - '${artifact}'
      - "--yes" # needed on cosign 2.0.0+

# Release notes
release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  footer: |
    ## Container Images
    
    Multi-arch images are available on GitHub Container Registry:
    
    ```bash
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}
    ```
    
    Supported architectures: `linux/amd64`, `linux/arm64`, `linux/arm/v7`
